In [ ]:
##practice python day 1

In [ ]:
import pandas as pd

load dataset

In [ ]:
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/22_Insurance_Data_Analytics_Project.xlsx",header=2)

read first 10 column of my dataset

In [ ]:
data.head(10)

,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status
0,POL00110,NaN,Life,73,313.10,0,No Claim
1,POL00229,2026-04-24 00:00:00,Motor,31,323.64,NaN,Pending
2,POL00098,2025-02-13 00:00:00,Life,37,333.82,4200.03,Pending
3,POL00220,2026-03-11 00:00:00,Property,31,449.01,1953.01,Approved
4,POL00088,2025-12-11 00:00:00,Health,28,378.73,0,No Claim
5,POL00112,2025-11-16 00:00:00,Life,43,528.80,3093.69,Approved
6,POL00167,2025-11-25 00:00:00,Life,53,354.41,391.32,Approved
7,POL00276,2025-05-01 00:00:00,Health,60,364.96,0,No Claim
8,POL00281,2025-09-05 00:00:00,Motor,23,339.63,0,No Claim
9,POL00066,2025-10-09 00:00:00,Property,62,395.53,4924.33,Pending

In [ ]:
data.tail(8)

,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status
292,POL00169,2025-09-19 00:00:00,Health,68,436.45,2970.52,Approved
293,POL00260,2025-03-28 00:00:00,Life,26,504.32,1353.33,Approved
294,POL00130,2026-01-16 00:00:00,Health,NaN,257.97,0,No Claim
295,POL00107,2025-09-29 00:00:00,Motor,46,-9.00,0,No Claim
296,POL00199,2026-02-01 00:00:00,Motor,NaN,287.26,0,No Claim
297,POL00258,2026-01-11 00:00:00,Health,30,387.67,0,No Claim
298,POL00136,2026-03-26 00:00:00,Life,20,398.51,0,No Claim
299,POL00234,2025-08-20 00:00:00,Life,32,316.87,0,No Claim

rows and colums of datasat

In [ ]:
data.shape

(300, 7)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Policy_ID     285 non-null    object
 1   Policy_Date   283 non-null    object
 2   Policy_Type   283 non-null    object
 3   Customer_Age  283 non-null    object
 4   Premium       285 non-null    float64
 5   Claim_Amount  281 non-null    object
 6   Claim_Status  284 non-null    object
dtypes: float64(1), object(6)
memory usage: 16.5+ KB

In [ ]:
data.describe()

          Premium
count  285.000000
mean   342.872877
std    110.454473
min     -9.000000
25%    282.630000
50%    349.590000
75%    406.970000
max    572.000000

In [ ]:
data.columns

Index(['Policy_ID', 'Policy_Date', 'Policy_Type', 'Customer_Age', 'Premium',
       'Claim_Amount', 'Claim_Status'],
      dtype='object')

In [ ]:
data.dtypes

Policy_ID        object
Policy_Date      object
Policy_Type      object
Customer_Age     object
Premium         float64
Claim_Amount     object
Claim_Status     object
dtype: object