###day 3 practice

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Supermarket_Practice_Data.xlsx")

In [ ]:
data = data.rename(columns={
    "Invoice_ID": "InvoiceID"
})

##Using replace

In [ ]:
data['Payment_Method'].value_counts()

Payment_Method
EVC Plus         31
Bank Transfer    31
Cash             31
Card             29
Name: count, dtype: int64

In [ ]:
data["Payment_Method"]=data["Payment_Method"].replace("evc plus","EVC Plus")

In [ ]:
data.columns

Index(['InvoiceID', 'Sale_Date', 'Product', 'Category', 'City', 'Quantity',
       'Unit_Price', 'Discount', 'Revenue', 'Cost', 'Payment_Method',
       'Customer_Type', 'Data_Quality_Issues'],
      dtype='object')

In [ ]:
data['City'].value_counts()

City
Mogadishu    39
Garowe       31
Kismayo      28
Hargeisa     23
Name: count, dtype: int64

In [ ]:
data["City"]=data["City"].replace("Mogadisho","Mogadishu")

In [36]:
data['Category'].value_counts()

Category
Snacks           27
Beverages        23
Dairy            20
Grocery          19
Produce          13
Meat              8
Bakery            6
Personal Care     6
Name: count, dtype: int64

In [35]:
# Replace the value "grocery" with "Grocery" in the Category column
data["Category"] = data["Category"].replace("grocery", "Grocery")

##Numerical Replacement

In [27]:
data["Quantity"] = data["Quantity"].replace(
{ 1: "Low",
 2: "Medium",
3: "more" })

In [28]:
data.head()

,InvoiceID,Sale_Date,Product,Category,City,Quantity,Unit_Price,Discount,Revenue,Cost,Payment_Method,Customer_Type,Data_Quality_Issues
0,INV-1001,2026-01-21,Eggs 12pcs,Dairy,Garowe,4.0,3.30,0.05,12.54,10.24,EVC Plus,New,Inconsistent Payment Label
1,INV-1002,2026-06-01,Eggs 12pcs,Dairy,Garowe,more,2.94,0.00,8.82,6.53,EVC Plus,Regular,Inconsistent Payment Label
2,INV-1003,2026-01-21,Bread,Bakery,Mogadishu,8.0,0.89,0.02,6.98,4.42,Bank Transfer,Member,NaN
3,INV-1004,2026-06-19,Apple 1kg,Produce,Kismayo,5.0,2.42,0.00,12.10,8.77,Bank Transfer,New,NaN
4,INV-1005,2026-02-20,Rice 5kg,Grocery,Garowe,4.0,6.69,0.10,24.08,19.09,Cash,Regular,NaN

##Removing Unnecessary Columns

In [30]:
data.drop(
columns=["InvoiceID"]
)

,Sale_Date,Product,Category,City,Quantity,Unit_Price,Discount,Revenue,Cost,Payment_Method,Customer_Type,Data_Quality_Issues
0,2026-01-21,Eggs 12pcs,Dairy,Garowe,4.0,3.30,0.05,12.54,10.24,EVC Plus,New,Inconsistent Payment Label
1,2026-06-01,Eggs 12pcs,Dairy,Garowe,more,2.94,0.00,8.82,6.53,EVC Plus,Regular,Inconsistent Payment Label
2,2026-01-21,Bread,Bakery,Mogadishu,8.0,0.89,0.02,6.98,4.42,Bank Transfer,Member,NaN
3,2026-06-19,Apple 1kg,Produce,Kismayo,5.0,2.42,0.00,12.10,8.77,Bank Transfer,New,NaN
4,2026-02-20,Rice 5kg,Grocery,Garowe,4.0,6.69,0.10,24.08,19.09,Cash,Regular,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
117,2026-01-05,Water 1.5L,Beverages,Garowe,more,0.64,0.02,1.88,1.36,EVC Plus,Member,Inconsistent Payment Label
118,2026-01-17,Orange Juice 1L,Beverages,Mogadishu,Medium,1.94,0.05,3.69,2.93,Card,New,NaN
119,2026-03-10,Orange Juice 1L,Beverages,Hargeisa,6.0,2.11,0.02,12.41,8.12,Bank Transfer,Member,NaN
120,2026-02-10,Orange Juice 1L,Beverages,Kismayo,more,2.30,0.05,6.55,4.38,Card,Regular,NaN
121,2026-06-22,Orange Juice 1L,Beverages,Kismayo,5.0,1.93,0.05,9.17,6.95,Cash,Member,NaN

##hanging Data Types

In [33]:
data.dtypes

InvoiceID                      object
Sale_Date              datetime64[ns]
Product                        object
Category                       object
City                           object
Quantity                        Int64
Unit_Price                    float64
Discount                      float64
Revenue                       float64
Cost                          float64
Payment_Method                 object
Customer_Type                  object
Data_Quality_Issues            object
dtype: object

In [32]:
data["Quantity"] = pd.to_numeric(data["Quantity"],
errors='coerce').astype('Int64')

##str.strip()
 The .str.strip() method removes unnecessary spaces from the beginning and end of text values

In [34]:
data["Category"] = data["Category"].str.strip()

##str.lower() & .str.upper()
The .str.lower()method converts text to lowercase

In [37]:
data["Category"] = data["Category"].str.title()